-- Fotografia [ent3]
drop table `fotografia`;
-- Ospite [ent2]
drop table `ospite`;
-- Nazione [ent19]
drop table `nazione`;
-- Donazione [ent18]
drop table `donazione`;
-- RaccoltaFondi [ent17]
drop table `raccoltafondi`;
-- EventoInEvidenza [ent16]
drop table `eventoinevidenza`;
-- Posizione [ent15]
drop table `posizione`;
-- Qualifica [ent14]
drop table `qualifica`;
-- Indirizzo [ent13]
drop table `indirizzo`;
-- Amministratore [ent12]
drop table `amministratore`;
-- Alumno [ent11]
drop table `alumno`;
-- Staff [ent10]
drop table `staff`;
-- Evento [ent1]
drop table `evento`;
-- Utente [User]
drop table `utente`;
-- Modulo [Module]
drop table `modulo`;
-- Gruppo [Group]
drop table `gruppo`;
